//go:build !ignore_autogenerated

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *HermesImageSelector) DeepCopyInto(out *HermesImageSelector) {
	*out = *in
}

func (in *HermesImageSelector) DeepCopy() *HermesImageSelector {
	if in == nil {
		return nil
	}
	out := new(HermesImageSelector)
	in.DeepCopyInto(out)
	return out
}

func (in *HermesImageStatus) DeepCopyInto(out *HermesImageStatus) {
	*out = *in
	in.LastBuildTime.DeepCopyInto(&out.LastBuildTime)
}

func (in *HermesImageStatus) DeepCopy() *HermesImageStatus {
	if in == nil {
		return nil
	}
	out := new(HermesImageStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *HermesPolicy) DeepCopyInto(out *HermesPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *HermesPolicy) DeepCopy() *HermesPolicy {
	if in == nil {
		return nil
	}
	out := new(HermesPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *HermesPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HermesPolicyList) DeepCopyInto(out *HermesPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HermesPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HermesPolicyList) DeepCopy() *HermesPolicyList {
	if in == nil {
		return nil
	}
	out := new(HermesPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *HermesPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HermesPolicySpec) DeepCopyInto(out *HermesPolicySpec) {
	*out = *in
	if in.ImageSelectors != nil {
		in, out := &in.ImageSelectors, &out.ImageSelectors
		*out = make([]HermesImageSelector, len(*in))
		copy(*out, *in)
	}
	if in.Platforms != nil {
		in, out := &in.Platforms, &out.Platforms
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *HermesPolicySpec) DeepCopy() *HermesPolicySpec {
	if in == nil {
		return nil
	}
	out := new(HermesPolicySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HermesPolicyStatus) DeepCopyInto(out *HermesPolicyStatus) {
	*out = *in
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = make([]HermesImageStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HermesPolicyStatus) DeepCopy() *HermesPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(HermesPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
