defaultBaseImage: cgr.dev/chainguard/static:latest

builds:
  - id: hermes-controller
    dir: .
    main: ./cmd/controller
    env:
      - CGO_ENABLED=1
    ldflags:
      - -linkmode external
      - -extldflags "-static"
      - -X github.com/cloudpilot-ai/hermes/pkg/common/version.Version={{ .Env.GIT_VERSION }}
      - -X github.com/cloudpilot-ai/hermes/pkg/common/version.Revision={{ .Env.GIT_COMMIT }}
